// <auto-generated />
using System;
using Apps.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Apps.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20240305041512_seed-data-test")]
    partial class seeddatatest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Apps.Models.Db.Test01", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Created")
                        .HasColumnOrder(3);

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nama")
                        .HasColumnOrder(1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("Status")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Updated")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.ToTable("Test01");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test01",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test02",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test03",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test04",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test05",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test06",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test07",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test08",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test09",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test10",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test11",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test12",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test13",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test14",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test15",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test16",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test17",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test18",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test19",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test20",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test21",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test22",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test23",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test24",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            Created = new DateTime(2024, 1, 1, 14, 40, 52, 531, DateTimeKind.Unspecified),
                            Nama = "Test25",
                            Status = (short)1,
                            Updated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
